"""
Sentinel AI — Base Workflow & Step Interfaces

Defines BaseWorkflow abstract strategy interface, WorkflowStepDefinition,
WorkflowContext, and WorkflowStepOutput dataclasses.
"""

import abc
import uuid
from dataclasses import dataclass, field
from typing import Any

from app.models.enums import WorkflowState, WorkflowStepState, WorkflowType


@dataclass
class WorkflowStepDefinition:
    """Dataclass defining a step inside a Workflow DAG."""

    step_name: str
    step_type: str
    depends_on: list[str] = field(default_factory=list)
    max_retries: int = 3
    timeout_seconds: int = 300


@dataclass
class WorkflowStepOutput:
    """Dataclass holding output generated by an individual workflow step."""

    step_name: str
    state: WorkflowStepState
    execution_time_ms: float = 0.0
    logs: str = ""
    outputs: dict[str, Any] = field(default_factory=dict)


@dataclass
class WorkflowContext:
    """Telemetry context container passed through a workflow run."""

    workflow_type: WorkflowType
    dataset_id: uuid.UUID | None = None
    title: str = "Sentinel AI Workflow"
    parameters: dict[str, Any] = field(default_factory=dict)
    step_outputs: dict[str, WorkflowStepOutput] = field(default_factory=dict)


@dataclass
class RawWorkflowCandidate:
    """Raw output candidate produced by a workflow strategy."""

    workflow_type: WorkflowType
    title: str
    state: WorkflowState
    step_definitions: list[WorkflowStepDefinition] = field(default_factory=list)
    step_outputs: list[WorkflowStepOutput] = field(default_factory=list)


class BaseWorkflow(abc.ABC):
    """Abstract strategy interface for workflow orchestration pipelines."""

    @property
    @abc.abstractmethod
    def workflow_type(self) -> WorkflowType:
        """Return the unique WorkflowType enum key."""
        pass

    @abc.abstractmethod
    def get_step_definitions(self) -> list[WorkflowStepDefinition]:
        """
        Return DAG step definitions for this workflow.

        Returns:
            List of WorkflowStepDefinition instances defining DAG dependencies.
        """
        pass
