"""
Sentinel AI — Base Analyzer Strategy Interface

Defines BaseAnalyzer abstract strategy interface, AnalysisContext, EvidenceCandidate,
and RawDiagnosticResult dataclasses.
"""

import abc
import uuid
from dataclasses import dataclass, field
from typing import Any

from app.models.enums import AnalysisType, ValidationSeverity


@dataclass
class EvidenceCandidate:
    """Dataclass representing supporting evidence produced by an Analyzer."""

    evidence_type: str
    title: str
    description: str
    evidence_payload: dict[str, Any] = field(default_factory=dict)
    weight: float = 1.0


@dataclass
class AnalysisContext:
    """Context container supplied to Root Cause Analyzers."""

    analysis_type: AnalysisType
    target_entity_type: str
    target_entity_id: str
    dataset_id: uuid.UUID | None = None
    validation_run: dict[str, Any] | None = None
    validation_results: list[dict[str, Any]] = field(default_factory=list)
    dataset_profile: dict[str, Any] | None = None
    drift_run: dict[str, Any] | None = None
    drift_results: list[dict[str, Any]] = field(default_factory=list)
    alerts: list[dict[str, Any]] = field(default_factory=list)
    jobs: list[dict[str, Any]] = field(default_factory=list)
    schema_history: list[dict[str, Any]] = field(default_factory=list)


@dataclass
class RawDiagnosticResult:
    """Output generated by deterministic rule-based evaluation before LLM synthesis."""

    summary: str
    probable_root_cause: str
    confidence_score: float
    severity: ValidationSeverity
    affected_components: list[str] = field(default_factory=list)
    recommended_actions: list[str] = field(default_factory=list)
    evidences: list[EvidenceCandidate] = field(default_factory=list)


class BaseAnalyzer(abc.ABC):
    """Abstract strategy interface for automated AI Root Cause Analyzers."""

    @property
    @abc.abstractmethod
    def analysis_type(self) -> AnalysisType:
        """Return the unique AnalysisType enum key."""
        pass

    @abc.abstractmethod
    def analyze(self, context: AnalysisContext) -> RawDiagnosticResult:
        """
        Perform deterministic diagnostic analysis on supplied telemetry context.

        Args:
            context: AnalysisContext containing telemetry data from validations, drift, jobs, alerts.

        Returns:
            RawDiagnosticResult containing findings, confidence score, and evidence candidates.
        """
        pass
