"""
Sentinel AI — Base Forecast Strategy Interface

Defines BaseForecastStrategy abstract strategy interface, ForecastContext,
ForecastDatapoint, and RawForecastCandidate dataclasses.
"""

import abc
import uuid
from dataclasses import dataclass, field
from typing import Any

from app.models.enums import ForecastType, RiskLevel, TrendDirection


@dataclass
class ForecastDatapoint:
    """Dataclass holding an individual predicted metric datapoint."""

    target_metric: str
    predicted_value: float
    confidence_interval_lower: float
    confidence_interval_upper: float
    trend_direction: TrendDirection
    risk_level: RiskLevel
    explanation: str
    preventive_actions: list[str] = field(default_factory=list)


@dataclass
class ForecastContext:
    """Telemetry context container supplied to forecasting strategies."""

    forecast_type: ForecastType
    dataset_id: uuid.UUID | None = None
    historical_series: list[float] = field(default_factory=list)
    horizon_days: int = 7
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class RawForecastCandidate:
    """Raw output generated by a forecast strategy."""

    forecast_type: ForecastType
    algorithm_name: str
    overall_risk_level: RiskLevel
    summary: str
    datapoints: list[ForecastDatapoint] = field(default_factory=list)


class BaseForecastStrategy(abc.ABC):
    """Abstract strategy interface for predictive observability and risk forecasting."""

    @property
    @abc.abstractmethod
    def forecast_type(self) -> ForecastType:
        """Return the unique ForecastType enum key."""
        pass

    @abc.abstractmethod
    def generate(self, context: ForecastContext) -> RawForecastCandidate:
        """
        Generate predictive forecast from context telemetry series.

        Args:
            context: ForecastContext containing historical time series data.

        Returns:
            RawForecastCandidate containing projected metric datapoints.
        """
        pass
