"""
Sentinel AI — Forecast Engine

Coordinates statistical model execution, confidence interval generation,
and risk level evaluation for predictive observability.
"""

import time
from dataclasses import dataclass, field

from app.forecasting.base_strategy import ForecastContext, ForecastDatapoint
from app.forecasting.executor import ForecastExecutor
from app.models.enums import ForecastType, RiskLevel


@dataclass
class ProcessedForecastResult:
    """Dataclass holding output generated by ForecastEngine."""

    forecast_type: ForecastType
    algorithm_name: str
    overall_risk_level: RiskLevel
    summary: str
    datapoints: list[ForecastDatapoint] = field(default_factory=list)
    execution_time_ms: float = 0.0


class ForecastEngine:
    """Orchestrates strategy execution and output processing."""

    def __init__(self, executor: ForecastExecutor | None = None) -> None:
        self._executor = executor or ForecastExecutor()

    def run_forecast(self, context: ForecastContext) -> ProcessedForecastResult:
        """
        Execute predictive forecasting pipeline.
        """
        start_time = time.perf_counter()

        raw = self._executor.execute_strategy(context)

        exec_ms = (time.perf_counter() - start_time) * 1000.0

        return ProcessedForecastResult(
            forecast_type=raw.forecast_type,
            algorithm_name=raw.algorithm_name,
            overall_risk_level=raw.overall_risk_level,
            summary=raw.summary,
            datapoints=raw.datapoints,
            execution_time_ms=exec_ms,
        )
